import json
import re

from langchain_core.prompts import ChatPromptTemplate

from .llm import call_llm
from .vector_store import search
from .prompts import RAG_PROMPT
from utils.logger import get_logger
from config import settings



logger = get_logger(__name__)


def parse_llm_response(response: str) -> dict:
    """
    Parse and validate the JSON response returned by the LLM.

    The model is instructed to return JSON, but this also handles
    Markdown code fences in case the model returns ```json ... ```.
    """

    response = response.strip()

    # Remove optional Markdown code fences
    response = re.sub(r"^```(?:json)?\s*", "", response)
    response = re.sub(r"\s*```$", "", response)

    try:
        result = json.loads(response)
    except json.JSONDecodeError:
        logger.exception("LLM returned invalid JSON")
        raise ValueError("LLM returned invalid JSON")

    if not isinstance(result, dict):
        raise ValueError("LLM response must be a JSON object")

    if "answer" not in result:
        raise ValueError("LLM response missing 'answer' field")

    return result


def answer_question(question: str) -> dict:
    """
    Answer a question using retrieval-augmented generation.

    Sources are taken from the retrieved document metadata rather
    than generated by the LLM.
    """

    logger.info(
        "QA question received: %s",
        question
    )

    # Retrieve relevant chunks
    relevant_chunks = search(question)

    if not relevant_chunks:
        logger.info(
            "No sufficiently relevant context found for question."
        )

        return {
            "answer": "Not found in document",
            "sources": []
        }

    # Build context for the LLM
    context = "\n\n".join(
        chunk["text"]
        for chunk in relevant_chunks
    )

    # Extract trusted source filenames from retrieval metadata.
    # These are not generated by the LLM.
    sources = list(
        dict.fromkeys(
            chunk["metadata"]["source"]
            for chunk in relevant_chunks
        )
    )

    prompt_template = ChatPromptTemplate.from_template(
        RAG_PROMPT
    )

    prompt = prompt_template.format(
        context=context,
        question=question
    )

    response = call_llm(
        prompt,
        temperature=settings.rag_temperature,
        max_tokens=settings.rag_max_tokens
    )

    result = parse_llm_response(response)

    answer = result["answer"].strip()

    # If the LLM determines that the context does not answer
    # the question, do not return the retrieved sources.
    if answer == "Not found in document":
        sources = []

    logger.info(
        "QA response generated successfully. Sources: %s",
        sources
    )

    return {
        "answer": answer,
        "sources": sources
    }

